# Generated by Django 5.2 on 2025-12-17 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_add_product_name_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='The buyer in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='The product this conversation is about (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='products.product')),
                ('supplier', models.ForeignKey(help_text='The supplier in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads_as_supplier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='The message content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(help_text='The user who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(help_text='The thread this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatThreadParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField(blank=True, help_text='When the user last read this thread', null=True)),
                ('unread_count', models.PositiveIntegerField(default=0, help_text='Number of unread messages for this user')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.chatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(fields=('buyer', 'supplier', 'product'), name='unique_thread_with_product'),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', True)), fields=('buyer', 'supplier'), name='unique_thread_without_product'),
        ),
        migrations.AddConstraint(
            model_name='chatthreadparticipant',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='unique_thread_participant'),
        ),
    ]
