# Generated by Django 5.2.9 on 2025-12-16 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('products', '0002_add_product_name_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='The product being watched', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='products.product')),
                ('user', models.ForeignKey(help_text='The user who is watching this product', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'watchlist item',
                'verbose_name_plural': 'watchlist items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='watchlist_user_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_watchlist')],
            },
        ),
    ]
