# Generated by Django 5.2.9 on 2025-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Preferred payment method', max_length=100, null=True),
        ),
    ]
